[package]
name = "flavioso"
version = "0.1.0"
edition = "2021"

[dependencies]
flavio = { git = "https://github.com/mrbuche/flavio.git", rev = "01b91c8d702199d02447e7ccd90c063229d176c9", features = ["constitutive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
