[package]
name = "flavioso"
version = "0.1.0"
edition = "2021"

[dependencies]
flavio = { version = "=0.4.9", features = ["constitutive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"
