name = "Flavio"
uuid = "e03d936e-b143-417e-99f1-948e30aaf057"
authors = ["Michael Robert Buche <dev@mrbuche.com>"]
version = "0.1.2"

[compat]
Aqua = "0"
Documenter = "1"
JuliaFormatter = "1"
LinearAlgebra = "1"
Test = "1"
julia = "1.6 - 1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Aqua", "JuliaFormatter", "LinearAlgebra", "Test"]
