name = "Flavio"
uuid = "e03d936e-b143-417e-99f1-948e30aaf057"
authors = ["Michael Robert Buche <dev@mrbuche.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
