name = "Flavio"
uuid = "e03d936e-b143-417e-99f1-948e30aaf057"
authors = ["Michael Robert Buche <dev@mrbuche.com>"]
version = "0.1.0"

[compat]
julia = "1.6 - 1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
