name: Pages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]
jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - name: Install
        run: julia --project=docs/ --color=yes -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
      - name: Dev
        run: |
          julia --project=docs/ --color=yes docs/make.jl
          mkdir -p _site/julia/docs/latest/
          cp -r docs/build/* _site/julia/docs/latest/
      - name: Deploy
        uses: actions/upload-pages-artifact@v2