name: Test
on:
  pull_request:
    branches: [ main ]
jobs:
  Julia:
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Test
        run: julia --color=yes -e 'using Pkg; Pkg.develop(path="."); Pkg.build("Flavio"); Pkg.test("Flavio")'
